version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: royaltaxi
      POSTGRES_USER: royaltaxi_user
      POSTGRES_PASSWORD: royaltaxi_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U royaltaxi_user -d royaltaxi"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and rate limiting
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Main application
  app:
    build: .
    environment:
      DATABASE_URL: postgresql://royaltaxi_user:royaltaxi_password@db:5432/royaltaxi
      REDIS_URL: redis://redis:6379
      FIREBASE_CREDENTIALS_PATH: /app/firebase-credentials.json
    ports:
      - "8000:8000"
    volumes:
      - ./firebase-credentials.json:/app/firebase-credentials.json:ro
      - ./uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  # Celery worker for background tasks
  celery-worker:
    build: .
    command: celery -A main.celery_app worker --loglevel=info
    environment:
      DATABASE_URL: postgresql://royaltaxi_user:royaltaxi_password@db:5432/royaltaxi
      REDIS_URL: redis://redis:6379
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
      - redis
      - app

  # Celery beat for scheduled tasks
  celery-beat:
    build: .
    command: celery -A main.celery_app beat --loglevel=info
    environment:
      DATABASE_URL: postgresql://royaltaxi_user:royaltaxi_password@db:5432/royaltaxi
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
      - app

  # Flower for Celery monitoring
  flower:
    build: .
    command: flower -A main.celery_app --port=5555
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: postgresql://royaltaxi_user:royaltaxi_password@db:5432/royaltaxi
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:
