services:
  app:
    build:
      context: .
      target: development
    container_name: royaltaxi-app
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://royaltaxi:royaltaxi123@db:5432/royaltaxi
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - royaltaxi-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15-alpine
    container_name: royaltaxi-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: royaltaxi
      POSTGRES_PASSWORD: royaltaxi123
      POSTGRES_DB: royaltaxi
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"  # ⚠️ Tashqi portni 5433 qildik
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U royaltaxi -d royaltaxi"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - royaltaxi-network

  redis:
    image: redis:7-alpine
    container_name: royaltaxi-redis
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "your_redis_password"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "your_redis_password", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - royaltaxi-network

networks:
  royaltaxi-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
